#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-stringex
Version  : 2.6.1
Release  : 9
URL      : https://rubygems.org/downloads/stringex-2.6.1.gem
Source0  : https://rubygems.org/downloads/stringex-2.6.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-activemodel
BuildRequires : rubygem-activerecord
BuildRequires : rubygem-activesupport
BuildRequires : rubygem-arel
BuildRequires : rubygem-builder
BuildRequires : rubygem-i18n
BuildRequires : rubygem-jeweler
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-sqlite3
BuildRequires : rubygem-test-unit
BuildRequires : rubygem-thread_safe
BuildRequires : rubygem-tzinfo

%description
= Stringex {<img src="https://codeclimate.com/github/rsl/stringex.png" />}[https://codeclimate.com/github/rsl/stringex] {<img src="https://travis-ci.org/rsl/stringex.png?branch=master" alt="Build Status" />}[https://travis-ci.org/rsl/stringex] {<img src="https://badge.fury.io/rb/stringex.svg" alt="Gem Version" />}[http://badge.fury.io/rb/stringex]

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n stringex-2.6.1
gem spec %{SOURCE0} -l --ruby > rubygem-stringex.gemspec

%build
export LANG=C
gem build rubygem-stringex.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
stringex-2.6.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/stringex-2.5.2 && rake -I.:lib test && popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/stringex-2.6.1.gem
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/MIT-LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/VERSION
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/init.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/acts_as_url.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/acts_as_url/adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/acts_as_url/adapter/active_record.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/acts_as_url/adapter/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/acts_as_url/adapter/data_mapper.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/acts_as_url/adapter/mongoid.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/configuration.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/configuration/acts_as_url.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/configuration/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/configuration/configurator.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/configuration/string_extensions.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/configuration_lite.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/core_ext.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/localization.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/localization/backend/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/localization/backend/i18n.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/localization/backend/internal.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/localization/conversion_expressions.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/localization/converter.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/localization/default_conversions.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/rails/railtie.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/string_extensions.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x00.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x01.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x02.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x03.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x04.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x05.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x06.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x07.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x09.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x0a.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x0b.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x0c.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x0d.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x0e.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x0f.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x10.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x11.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x12.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x13.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x14.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x15.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x16.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x17.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x18.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x1e.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x1f.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x20.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x21.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x22.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x23.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x24.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x25.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x26.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x27.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x28.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x2e.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x2f.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x30.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x31.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x32.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x33.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x4d.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x4e.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x4f.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x50.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x51.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x52.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x53.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x54.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x55.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x56.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x57.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x58.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x59.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x5a.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x5b.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x5c.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x5d.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x5e.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x5f.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x60.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x61.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x62.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x63.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x64.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x65.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x66.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x67.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x68.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x69.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x6a.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x6b.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x6c.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x6d.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x6e.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x6f.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x70.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x71.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x72.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x73.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x74.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x75.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x76.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x77.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x78.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x79.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x7a.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x7b.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x7c.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x7d.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x7e.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x7f.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x80.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x81.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x82.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x83.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x84.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x85.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x86.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x87.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x88.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x89.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x8a.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x8b.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x8c.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x8d.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x8e.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x8f.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x90.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x91.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x92.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x93.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x94.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x95.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x96.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x97.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x98.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x99.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x9a.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x9b.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x9c.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x9d.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x9e.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/x9f.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xa0.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xa1.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xa2.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xa3.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xa4.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xac.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xad.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xae.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xaf.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xb0.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xb1.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xb2.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xb3.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xb4.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xb5.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xb6.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xb7.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xb8.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xb9.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xba.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xbb.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xbc.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xbd.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xbe.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xbf.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xc0.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xc1.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xc2.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xc3.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xc4.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xc5.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xc6.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xc7.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xc8.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xc9.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xca.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xcb.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xcc.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xcd.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xce.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xcf.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xd0.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xd1.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xd2.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xd3.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xd4.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xd5.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xd6.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xd7.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xf9.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xfa.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xfb.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xfc.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xfd.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xfe.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/unidecoder_data/xff.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/lib/stringex_lite.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/locales/da.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/locales/de.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/locales/en.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/locales/fr.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/locales/nb.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/locales/nl.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/locales/no.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/locales/pl.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/locales/pt-BR.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/locales/ru.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/locales/sv.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/stringex.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/test/performance/localization_performance_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/test/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/test/unit/acts_as_url/adapter/activerecord.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/test/unit/acts_as_url/adapter/datamapper.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/test/unit/acts_as_url/adapter/mongoid.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/test/unit/acts_as_url_configuration_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/test/unit/acts_as_url_integration_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/test/unit/localization/da_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/test/unit/localization/de_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/test/unit/localization/default_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/test/unit/localization/en_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/test/unit/localization/fr_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/test/unit/localization/nl_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/test/unit/localization/pl_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/test/unit/localization/pt_br_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/test/unit/localization/ru_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/test/unit/localization/sv_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/test/unit/localization_18n_failure_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/test/unit/localization_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/test/unit/string_extensions_configuration_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/test/unit/string_extensions_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/test/unit/unicode_point_suite/basic_greek_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/test/unit/unicode_point_suite/basic_latin_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/test/unit/unicode_point_suite/codepoint_test_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/test/unit/unidecoder/bad_localization.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/test/unit/unidecoder/localization.yml
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/test/unit/unidecoder_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/stringex-2.6.1/test/unit/version_test.rb
/usr/lib64/ruby/gems/2.3.0/specifications/stringex-2.6.1.gemspec
