#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-stringex
Version  : 2.5.2
Release  : 5
URL      : https://rubygems.org/downloads/stringex-2.5.2.gem
Source0  : https://rubygems.org/downloads/stringex-2.5.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-activemodel
BuildRequires : rubygem-activerecord
BuildRequires : rubygem-activesupport
BuildRequires : rubygem-arel
BuildRequires : rubygem-builder
BuildRequires : rubygem-i18n
BuildRequires : rubygem-jeweler
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-sqlite3
BuildRequires : rubygem-test-unit
BuildRequires : rubygem-thread_safe
BuildRequires : rubygem-tzinfo

%description
= Stringex {<img src="https://codeclimate.com/github/rsl/stringex.png" />}[https://codeclimate.com/github/rsl/stringex] {<img src="https://travis-ci.org/rsl/stringex.png?branch=master" alt="Build Status" />}[https://travis-ci.org/rsl/stringex]

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n stringex-2.5.2
gem spec %{SOURCE0} -l --ruby > rubygem-stringex.gemspec

%build
gem build rubygem-stringex.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
stringex-2.5.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/stringex-2.5.2 && rake -I.:lib test && popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/stringex-2.5.2.gem
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Rails/cdesc-Rails.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/ActsAsUrlClassMethods/acts_as_url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/ActsAsUrlClassMethods/acts_as_url_configuration-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/ActsAsUrlClassMethods/cdesc-ActsAsUrlClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/ActsAsUrlClassMethods/included-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/ActsAsUrlClassMethods/initialize_urls-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/ActsAsUrlInstanceMethods/cdesc-ActsAsUrlInstanceMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/ActsAsUrlInstanceMethods/ensure_unique_url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/ActiveRecord/cdesc-ActiveRecord.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/ActiveRecord/klass_previous_instances-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/ActiveRecord/load-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/ActiveRecord/orm_class-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/add_new_record_url_owner_conditions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/add_scoped_url_owner_conditions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/base_url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/callback_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/cdesc-Base.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/configuration-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/create_callback-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/create_callbacks%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/create_method_to_callback-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/duplicate_for_base_url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/ensure_loadable-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/ensure_loadable-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/ensure_unique_url%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/ensure_unique_url_for%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/get_base_url_owner_conditions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/handle_blacklisted_url%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/handle_duplicate_url%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/handle_url%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/initialize_urls%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/instance-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/instance_from_db-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/is_blank%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/is_new%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/is_present%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/klass-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/klass_callback_method-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/klass_non_sync_url_callback_method-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/klass_sync_url_callback_method-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/loadable%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/loadable%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/modify_base_url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/orm_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/primary_key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/read_attribute-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/settings-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/url_attribute-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/url_attribute_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/url_owner_conditions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/url_owners-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/url_owners_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/write_attribute-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Base/write_url_attribute-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/DataMapper/cdesc-DataMapper.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/DataMapper/create_callback-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/DataMapper/instance_from_db-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/DataMapper/is_blank%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/DataMapper/is_new%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/DataMapper/is_present%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/DataMapper/klass_previous_instances-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/DataMapper/load-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/DataMapper/orm_class-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/DataMapper/primary_key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/DataMapper/read_attribute-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/DataMapper/url_owners-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/DataMapper/write_attribute-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Mongoid/add_new_record_url_owner_conditions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Mongoid/add_scoped_url_owner_conditions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Mongoid/cdesc-Mongoid.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Mongoid/get_base_url_owner_conditions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Mongoid/klass_previous_instances-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Mongoid/load-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/Mongoid/orm_class-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/add_loaded_adapter-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/cdesc-Adapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/first_available-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/Adapter/load_available-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/ActsAsUrl/cdesc-ActsAsUrl.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Configuration/ActsAsUrl/cdesc-ActsAsUrl.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Configuration/ActsAsUrl/default_settings-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Configuration/ActsAsUrl/default_settings-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Configuration/ActsAsUrl/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Configuration/ActsAsUrl/settings-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Configuration/ActsAsUrl/string_extensions_settings-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Configuration/Base/adapter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Configuration/Base/cdesc-Base.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Configuration/Base/configure-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Configuration/Base/default_settings-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Configuration/Base/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Configuration/Base/settings-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Configuration/Base/system_wide_customizations-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Configuration/Base/system_wide_customizations-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Configuration/Base/unconfigure%21-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Configuration/Base/valid_configuration_details-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Configuration/Configurator/cdesc-Configurator.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Configuration/Configurator/define_instance_method_for_configuration_wrapper-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Configuration/Configurator/klass-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Configuration/Configurator/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Configuration/StringExtensions/cdesc-StringExtensions.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Configuration/StringExtensions/default_settings-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Configuration/StringExtensions/default_settings-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Configuration/cdesc-Configuration.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Backend/Base/cdesc-Base.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Backend/Base/reset%21-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Backend/I18n/cdesc-I18n.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Backend/I18n/default_locale%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Backend/I18n/default_locale-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Backend/I18n/ensure_locales_enforced_or_not-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Backend/I18n/i18n_translations_for-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Backend/I18n/initial_translation-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Backend/I18n/load_translations-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Backend/I18n/locale%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Backend/I18n/locale-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Backend/I18n/reset_translations_cache-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Backend/I18n/store_translations-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Backend/I18n/translations-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Backend/I18n/with_locale-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Backend/I18nMissingTranslate/cdesc-I18nMissingTranslate.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Backend/I18nMissingTranslate/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Backend/I18nNotDefined/cdesc-I18nNotDefined.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Backend/I18nNotDefined/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Backend/Internal/cdesc-Internal.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Backend/Internal/default_locale%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Backend/Internal/default_locale-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Backend/Internal/initial_translation-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Backend/Internal/locale%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Backend/Internal/locale-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Backend/Internal/store_translations-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Backend/Internal/translations-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Backend/Internal/with_locale-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Backend/cdesc-Backend.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/ConversionExpressions/cdesc-ConversionExpressions.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Converter/abbreviations-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Converter/apostrophes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Converter/cdesc-Converter.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Converter/characters-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Converter/cleanup_accented_html_entities%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Converter/cleanup_characters%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Converter/cleanup_html_entities%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Converter/cleanup_smart_punctuation%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Converter/currencies-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Converter/ellipses-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Converter/ending_whitespace-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Converter/expressions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Converter/has_currencies%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Converter/html_entities-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Converter/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Converter/normalize_currency%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Converter/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Converter/smart_strip%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Converter/starting_whitespace-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Converter/string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Converter/strip%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Converter/strip_html_tags%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Converter/translate%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Converter/translate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/Converter/vulgar_fractions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/DefaultConversions/cdesc-DefaultConversions.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/backend%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/backend-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/cdesc-Localization.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/convert-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/default_conversion-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/default_locale%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/default_locale-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/ensure_i18n%21-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/i18n_present%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/initial_translation-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/locale%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/locale-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/reset%21-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/store_translations-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/translate-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/with_default_locale-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Localization/with_locale-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Railtie/cdesc-Railtie.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/StringExtensions/PublicClassMethods/cdesc-PublicClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/StringExtensions/PublicClassMethods/random-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/StringExtensions/PublicInstanceMethods/cdesc-PublicInstanceMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/StringExtensions/PublicInstanceMethods/collapse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/StringExtensions/PublicInstanceMethods/convert_accented_html_entities-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/StringExtensions/PublicInstanceMethods/convert_miscellaneous_characters-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/StringExtensions/PublicInstanceMethods/convert_miscellaneous_html_entities-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/StringExtensions/PublicInstanceMethods/convert_smart_punctuation-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/StringExtensions/PublicInstanceMethods/convert_vulgar_fractions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/StringExtensions/PublicInstanceMethods/limit-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/StringExtensions/PublicInstanceMethods/remove_formatting-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/StringExtensions/PublicInstanceMethods/replace_whitespace-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/StringExtensions/PublicInstanceMethods/stringex_convert-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/StringExtensions/PublicInstanceMethods/stringex_default_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/StringExtensions/PublicInstanceMethods/strip_html_tags-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/StringExtensions/PublicInstanceMethods/to_ascii-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/StringExtensions/PublicInstanceMethods/to_html-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/StringExtensions/PublicInstanceMethods/to_url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/StringExtensions/PublicInstanceMethods/whole_word_limit-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/StringExtensions/cdesc-StringExtensions.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/StringExtensions/configure-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/StringExtensions/unconfigure%21-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Unidecoder/cdesc-Unidecoder.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Unidecoder/code_group-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Unidecoder/decode-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Unidecoder/decoded-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Unidecoder/encode-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Unidecoder/from_yaml-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Unidecoder/get_codepoint-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Unidecoder/grouped_point-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Unidecoder/in_yaml_file-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Unidecoder/localized-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/Version/cdesc-Version.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/Stringex/cdesc-Stringex.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/page-MIT-LICENSE.ri
/usr/lib64/ruby/gems/2.2.0/doc/stringex-2.5.2/ri/page-README_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/MIT-LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/README.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/VERSION
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/init.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/acts_as_url.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/acts_as_url/adapter.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/acts_as_url/adapter/active_record.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/acts_as_url/adapter/base.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/acts_as_url/adapter/data_mapper.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/acts_as_url/adapter/mongoid.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/configuration.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/configuration/acts_as_url.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/configuration/base.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/configuration/configurator.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/configuration/string_extensions.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/configuration_lite.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/localization.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/localization/backend/base.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/localization/backend/i18n.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/localization/backend/internal.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/localization/conversion_expressions.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/localization/converter.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/localization/default_conversions.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/rails/railtie.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/string_extensions.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x00.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x01.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x02.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x03.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x04.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x05.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x06.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x07.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x09.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x0a.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x0b.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x0c.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x0d.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x0e.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x0f.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x10.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x11.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x12.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x13.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x14.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x15.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x16.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x17.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x18.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x1e.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x1f.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x20.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x21.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x22.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x23.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x24.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x25.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x26.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x27.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x28.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x2e.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x2f.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x30.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x31.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x32.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x33.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x4d.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x4e.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x4f.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x50.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x51.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x52.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x53.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x54.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x55.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x56.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x57.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x58.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x59.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x5a.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x5b.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x5c.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x5d.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x5e.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x5f.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x60.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x61.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x62.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x63.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x64.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x65.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x66.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x67.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x68.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x69.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x6a.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x6b.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x6c.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x6d.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x6e.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x6f.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x70.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x71.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x72.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x73.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x74.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x75.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x76.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x77.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x78.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x79.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x7a.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x7b.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x7c.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x7d.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x7e.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x7f.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x80.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x81.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x82.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x83.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x84.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x85.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x86.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x87.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x88.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x89.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x8a.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x8b.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x8c.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x8d.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x8e.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x8f.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x90.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x91.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x92.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x93.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x94.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x95.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x96.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x97.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x98.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x99.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x9a.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x9b.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x9c.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x9d.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x9e.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/x9f.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xa0.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xa1.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xa2.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xa3.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xa4.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xac.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xad.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xae.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xaf.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xb0.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xb1.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xb2.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xb3.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xb4.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xb5.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xb6.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xb7.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xb8.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xb9.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xba.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xbb.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xbc.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xbd.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xbe.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xbf.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xc0.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xc1.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xc2.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xc3.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xc4.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xc5.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xc6.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xc7.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xc8.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xc9.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xca.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xcb.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xcc.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xcd.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xce.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xcf.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xd0.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xd1.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xd2.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xd3.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xd4.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xd5.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xd6.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xd7.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xf9.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xfa.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xfb.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xfc.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xfd.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xfe.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/unidecoder_data/xff.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/lib/stringex_lite.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/locales/da.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/locales/de.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/locales/en.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/locales/nl.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/locales/pl.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/locales/pt-BR.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/locales/ru.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/locales/sv.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/stringex.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/test/performance/localization_performance_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/test/test_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/test/unit/acts_as_url/adapter/activerecord.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/test/unit/acts_as_url/adapter/datamapper.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/test/unit/acts_as_url/adapter/mongoid.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/test/unit/acts_as_url_configuration_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/test/unit/acts_as_url_integration_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/test/unit/localization/da_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/test/unit/localization/de_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/test/unit/localization/default_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/test/unit/localization/en_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/test/unit/localization/nl_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/test/unit/localization/pl_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/test/unit/localization/pt_br_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/test/unit/localization/ru_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/test/unit/localization/sv_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/test/unit/localization_18n_failure_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/test/unit/localization_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/test/unit/string_extensions_configuration_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/test/unit/string_extensions_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/test/unit/unicode_point_suite/basic_greek_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/test/unit/unicode_point_suite/basic_latin_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/test/unit/unicode_point_suite/codepoint_test_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/test/unit/unidecoder/bad_localization.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/test/unit/unidecoder/localization.yml
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/test/unit/unidecoder_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/stringex-2.5.2/test/unit/version_test.rb
/usr/lib64/ruby/gems/2.2.0/specifications/stringex-2.5.2.gemspec
